version: "3"
services:

  server:
    container_name: outside-server-container
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        OUTSIDE_SERVER_IGNORE_DATABASE_ERRORS: ${OUTSIDE_SERVER_IGNORE_DATABASE_ERRORS}
    ports:
      - "8080:8080"
    image: outside-server-image
    restart: always
    depends_on:
      - database

  pgadmin:
    container_name: pgadmin-container
    ports:
      - 8888:8888
    image: dpage/pgadmin4
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_LISTEN_PORT: 8888
    volumes:
      - ./data/pgadmin-container-data:/var/lib/pgadmin:rw  # `sudo chown -R 5050:5050 data/pgadmin-container-data/` to save session
    depends_on:
      - database

  database:
    container_name: outside-database-container
    ports:
      - 5432:5432
    image: postgres:14.5
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres-container-data:/var/lib/postgresql/data